name: Keep Streamlit Awake

on:
  schedule:
    - cron: "0 8 * * *"
  
  workflow_dispatch: 

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Esegue un curl verso le app per svegliarle
        run: |
          curl -L https://fuelpytracker-def.streamlit.app/_stcore/health
          curl -L https://fuelpytracker-demo.streamlit.app/_stcore/health